DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

-- =====================
-- UZYTKOWNIK
-- =====================
CREATE TABLE Uzytkownik
(
    id_uzytkownika   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login            VARCHAR(50),
    email            VARCHAR(100),
    haslo_hash       VARCHAR(255),
    status_konta     VARCHAR(20),
    data_rejestracji DATE
);

-- =====================
-- STUDENT
-- =====================
CREATE TABLE Student
(
    id_studenta      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_uzytkownika   INTEGER,
    nr_indeksu       VARCHAR(20),
    imie             VARCHAR(50),
    nazwisko         VARCHAR(50),
    kierunek         VARCHAR(100),
    semestr_aktualny INTEGER,
    FOREIGN KEY (id_uzytkownika) REFERENCES Uzytkownik (id_uzytkownika)
);

-- =====================
-- SEMESTR
-- =====================
CREATE TABLE Semestr
(
    id_semestru INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa       VARCHAR(20),
    data_od     DATE,
    data_do     DATE
);

-- =====================
-- PRZEDMIOT
-- =====================
CREATE TABLE Przedmiot
(
    id_przedmiotu  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod_przedmiotu VARCHAR(20),
    nazwa          VARCHAR(100),
    opis           VARCHAR(1000),
    ects           INTEGER
);

-- =====================
-- GRUPA PRZEDMIOTOWA
-- =====================
CREATE TABLE GrupaPrzedmiotowa
(
    id_grupy      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_przedmiotu INTEGER,
    nazwa_grupy   VARCHAR(50),
    semestr       INTEGER,
    limit_miejsc  INTEGER,
    FOREIGN KEY (id_przedmiotu) REFERENCES Przedmiot (id_przedmiotu)
);

-- =====================
-- ZAPIS NA PRZEDMIOT
-- =====================
CREATE TABLE ZapisNaPrzedmiot
(
    id_zapisu   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta INTEGER,
    id_grupy    INTEGER,
    data_zapisu DATE,
    status      VARCHAR(20),
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta),
    FOREIGN KEY (id_grupy) REFERENCES GrupaPrzedmiotowa (id_grupy)
);

-- =====================
-- OCENA
-- =====================
CREATE TABLE Ocena
(
    id_oceny         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta      INTEGER,
    id_grupy         INTEGER,
    id_semestru      INTEGER,
    wartosc          DECIMAL(3, 1),
    typ_oceny        VARCHAR(30),
    data_wystawienia DATE,
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta),
    FOREIGN KEY (id_grupy) REFERENCES GrupaPrzedmiotowa (id_grupy),
    FOREIGN KEY (id_semestru) REFERENCES Semestr (id_semestru)
);

-- =====================
-- PLATNOSC
-- =====================
CREATE TABLE Platnosc
(
    id_platnosci      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta       INTEGER,
    id_semestru       INTEGER,
    kwota             DECIMAL(10, 2),
    data_wymagalnosci DATE,
    data_wplaty       DATE,
    status            VARCHAR(20),
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta),
    FOREIGN KEY (id_semestru) REFERENCES Semestr (id_semestru)
);

-- =====================
-- KONTO BIBLIOTECZNE
-- =====================
CREATE TABLE KontoBiblioteczne
(
    id_konta_bibl   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta     INTEGER,
    status          VARCHAR(20),
    data_utworzenia DATE,
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta)
);

-- =====================
-- KSIAZKA
-- =====================
CREATE TABLE Ksiazka
(
    id_ksiazki INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tytul      VARCHAR(200),
    autor      VARCHAR(200),
    isbn       VARCHAR(20)
);

-- =====================
-- WYPOZYCZENIE
-- =====================
CREATE TABLE Wypozyczenie
(
    id_wypozyczenia   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_konta_bibl     INTEGER,
    id_ksiazki        INTEGER,
    data_wypozyczenia DATE,
    termin_zwrotu     DATE,
    data_zwrotu       DATE,
    status            VARCHAR(20),
    FOREIGN KEY (id_konta_bibl) REFERENCES KontoBiblioteczne (id_konta_bibl),
    FOREIGN KEY (id_ksiazki) REFERENCES Ksiazka (id_ksiazki)
);

-- =====================
-- ZAJECIA
-- =====================
CREATE TABLE Zajecia
(
    id_zajec       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_grupy       INTEGER,
    id_semestru    INTEGER,
    dzien_tygodnia SMALLINT,
    godzina_od     TIME,
    godzina_do     TIME,
    sala           VARCHAR(20),
    FOREIGN KEY (id_grupy) REFERENCES GrupaPrzedmiotowa (id_grupy),
    FOREIGN KEY (id_semestru) REFERENCES Semestr (id_semestru)
);

-- =====================
-- POWIADOMIENIE
-- =====================
CREATE TABLE PowiadomieniePlan
(
    id_powiadomienia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta      INTEGER,
    tresc            VARCHAR(1000),
    data_wyslania    TIMESTAMP,
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta)
);
