DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

-- =====================
-- UZYTKOWNIK
-- =====================
CREATE TABLE Uzytkownik
(
    id_uzytkownika   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login            VARCHAR(50) NOT NULL UNIQUE,
    email            VARCHAR(100) NOT NULL UNIQUE,
    haslo_hash       VARCHAR(255) NOT NULL,
    status_konta     VARCHAR(20) NOT NULL,
    data_rejestracji DATE NOT NULL
);

-- =====================
-- STUDENT
-- =====================
CREATE TABLE Student
(
    id_studenta      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_uzytkownika   INTEGER NOT NULL UNIQUE,
    nr_indeksu       VARCHAR(20) NOT NULL UNIQUE,
    imie             VARCHAR(50) NOT NULL,
    nazwisko         VARCHAR(50) NOT NULL,
    kierunek         VARCHAR(100) NOT NULL,
    semestr_aktualny INTEGER,
    FOREIGN KEY (id_uzytkownika) REFERENCES Uzytkownik (id_uzytkownika)
);

-- =====================
-- SEMESTR
-- =====================
CREATE TABLE Semestr
(
    id_semestru INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa       VARCHAR(20) NOT NULL UNIQUE,
    data_od     DATE NOT NULL,
    data_do     DATE NOT NULL
);

-- =====================
-- PRZEDMIOT
-- =====================
CREATE TABLE Przedmiot
(
    id_przedmiotu  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kod_przedmiotu VARCHAR(20) NOT NULL UNIQUE,
    nazwa          VARCHAR(100) NOT NULL,
    opis           VARCHAR(1000),
    ects           INTEGER NOT NULL
);

-- =====================
-- GRUPA PRZEDMIOTOWA
-- =====================
CREATE TABLE GrupaPrzedmiotowa
(
    id_grupy      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_przedmiotu INTEGER NOT NULL,
    nazwa_grupy   VARCHAR(50) NOT NULL,
    semestr       INTEGER NOT NULL,
    limit_miejsc  INTEGER NOT NULL,
    FOREIGN KEY (id_przedmiotu) REFERENCES Przedmiot (id_przedmiotu)
);

-- =====================
-- ZAPIS NA PRZEDMIOT
-- =====================
CREATE TABLE ZapisNaPrzedmiot
(
    id_zapisu   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta INTEGER NOT NULL,
    id_grupy    INTEGER NOT NULL,
    data_zapisu DATE NOT NULL,
    status      VARCHAR(20) NOT NULL,
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta),
    FOREIGN KEY (id_grupy) REFERENCES GrupaPrzedmiotowa (id_grupy)
);

-- =====================
-- OCENA
-- =====================
CREATE TABLE Ocena
(
    id_oceny         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta      INTEGER NOT NULL,
    id_grupy         INTEGER NOT NULL,
    id_semestru      INTEGER NOT NULL,
    wartosc          DECIMAL(4,2) NOT NULL,
    typ_oceny        VARCHAR(30) NOT NULL,
    data_wystawienia DATE NOT NULL,
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta),
    FOREIGN KEY (id_grupy) REFERENCES GrupaPrzedmiotowa (id_grupy),
    FOREIGN KEY (id_semestru) REFERENCES Semestr (id_semestru)
);

-- =====================
-- PLATNOSC
-- =====================
CREATE TABLE Platnosc
(
    id_platnosci      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta       INTEGER NOT NULL,
    id_semestru       INTEGER NOT NULL,
    kwota             DECIMAL(10,2) NOT NULL,
    data_wymagalnosci DATE NOT NULL,
    data_wplaty       DATE,
    status            VARCHAR(20) NOT NULL,
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta),
    FOREIGN KEY (id_semestru) REFERENCES Semestr (id_semestru)
);

-- =====================
-- KONTO BIBLIOTECZNE
-- =====================
CREATE TABLE KontoBiblioteczne
(
    id_konta_bibl   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta     INTEGER NOT NULL UNIQUE,
    status          VARCHAR(20) NOT NULL,
    data_utworzenia DATE NOT NULL,
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta)
);

-- =====================
-- KSIAZKA
-- =====================
CREATE TABLE Ksiazka
(
    id_ksiazki INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tytul      VARCHAR(200) NOT NULL,
    autor      VARCHAR(200) NOT NULL,
    isbn       VARCHAR(20)
);

-- =====================
-- WYPOZYCZENIE
-- =====================
CREATE TABLE Wypozyczenie
(
    id_wypozyczenia   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_konta_bibl     INTEGER NOT NULL,
    id_ksiazki        INTEGER NOT NULL,
    data_wypozyczenia DATE NOT NULL,
    termin_zwrotu     DATE NOT NULL,
    data_zwrotu       DATE,
    status            VARCHAR(20) NOT NULL,
    FOREIGN KEY (id_konta_bibl) REFERENCES KontoBiblioteczne (id_konta_bibl),
    FOREIGN KEY (id_ksiazki) REFERENCES Ksiazka (id_ksiazki)
);

-- =====================
-- ZAJECIA
-- =====================
CREATE TABLE Zajecia
(
    id_zajec       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_grupy       INTEGER NOT NULL,
    id_semestru    INTEGER NOT NULL,
    dzien_tygodnia SMALLINT NOT NULL,
    godzina_od     TIME NOT NULL,
    godzina_do     TIME NOT NULL,
    sala           VARCHAR(20) NOT NULL,
    FOREIGN KEY (id_grupy) REFERENCES GrupaPrzedmiotowa (id_grupy),
    FOREIGN KEY (id_semestru) REFERENCES Semestr (id_semestru)
);

-- =====================
-- POWIADOMIENIE
-- =====================
CREATE TABLE Powiadomienie
(
    id_powiadomienia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta      INTEGER NOT NULL,
    tresc            TEXT NOT NULL,
    data_wyslania    TIMESTAMP NOT NULL,
    FOREIGN KEY (id_studenta) REFERENCES Student (id_studenta)
);